const shortcuts  = {
  SHORTCUT_OPEN_TAB: 'SHORTCUT_OPEN_TAB',
  SHORTCUT_CLOSE_TAB: 'SHORTCUT_CLOSE_TAB',
  SHORTCUT_NEXT_TAB: 'SHORTCUT_NEXT_TAB',
  SHORTCUT_PREV_TAB: 'SHORTCUT_PREV_TAB',
  SHORTCUT_RELOAD_TAB: 'SHORTCUT_RELOAD_TAB',
  SHORTCUT_FULL_RELOAD_TAB: 'SHORTCUT_FULL_RELOAD_TAB',
  SHORTCUT_FIND_IN_PAGE: 'SHORTCUT_FIND_IN_PAGE',
  SHORTCUT_RELOAD_WINDOW: 'SHORTCUT_RELOAD_WINDOW',
  SHORTCUT_TOGGLE_DEVTOOLS: 'SHORTCUT_TOGGLE_DEVTOOLS'
}

module.exports = { shortcuts }