name: Build electron distributables

on:
  push:
    tags:
      - 'v*'

jobs:
  build-electron :
    runs-on: macos-13

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies ⚙
        run: |
          npm install
          brew install --cask xquartz
          brew tap homebrew/cask
          brew install --cask --no-quarantine wine-stable
          ln -s $(which wine) $(dirname `which wine`)/wine64

      - name: Build electron app 🔧
        run: WINEPREFIX=~/wine npm run build:all

      - name: Package electron app in different versions and architectures 🔧
        run: WINEPREFIX=~/wine VERSION=${{ github.ref_name }} npm run package

      - name: Check builds dir
        run: ls release dist

      - name: Upload release for Linux
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "./release/HyBro-${{ github.ref_name }}-Linux.zip"
          tag: ${{ github.ref }}
          release_name: "HyBro, ${{ github.ref_name }}"
          overwrite: true

      - name: Upload release for MacOSX
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "./release/HyBro-${{ github.ref_name }}-MacOSX.zip"
          tag: ${{ github.ref }}
          release_name: "HyBro, ${{ github.ref_name }}"
          overwrite: true

      - name: Upload release for Windows
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "./release/HyBro-${{ github.ref_name }}-Windows.zip"
          tag: ${{ github.ref }}
          release_name: "HyBro, ${{ github.ref_name }}"
          overwrite: true

