name: Build electron distributables

on: 
  # release:
  #   types: [published]
  push: 
    branches:
      - autobuild

jobs:
  build-electron :
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
        with:
          ref: main
          persist-credentials: false

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3

      - name: Install dependencies ⚙
        run: npm install

      - name: Build electron app 🔧
        run: npm run build:all

      - name: Package electron app in different versions and architectures 🔧
        run: npm run package

      - name: Check builds dir
        run: ls release dist

      - name: Upload release for Linux
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "./release/Hybro-Linux.zip"
          asset_name: hybro.for.linux.zip
          tag: ${{ github.ref }}

      - name: Upload release for MacOSX
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "./release/Hybro-MacOSX.zip"
          asset_name: hybro.for.macosx.zip
          tag: ${{ github.ref }}

      - name: Upload release for Windows
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "./release/Hybro-Windows.zip"
          asset_name: hybro.for.windows.zip
          tag: ${{ github.ref }}

